### ISSUE TITLE
synapses_STDP.py is identical as synapses_homeo.py

### ISSUE THREAD

**Issue by shhong** [brian-team/brian-material#1]
In 2014-CNS-tutorial/03-hands-on-tutorial, synapses_STDP.py is identical as synapses_homeo.py.

**Comment by mstimberg** [comment]
Hi and thanks for notifying us. The files are not literally identical, but indeed they seem to do the same thing and `synapses_STDP.py` does not actually implement an STDP rule. I replaced the file with an actual STDP example now.
